### ISSUE TITLE
Switch to ECR Private for git sha tagged images

### ISSUE THREAD

**Issue by dwilkie** [somleng/somleng#1046]
## Description of Problem

Currently we use a combination of ECR Public and Github to store our Docker images. On ECR Public we tag the image as the github sha and update the task definition so that ECS can easily rollback to previous versions. On Gitub we push the latest and staging tags. This causes our ECR public repository to keep growing on every merge to develop or master branch it will create a new tag. AWS doesn't support lifecycle management for ECR public repositories.

## Solution

Switch to ECR Private and push the docker tags tagged with the github sha. Then we can configure a ECR lifecycle policy (https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html) to remove the old tags.

On Github we only need to push the latest tag. In the future when we start releasing versions of Somleng we can also push versioned tags to github too.

## Additional Info

```rb
# Delete all images from repository
# Need to run this multiple times because it doesn't handle pagination
# This is needed so Terraform can delete the public repository as it won't delete it if there are existing images.

require "json"

repository_name = "somleng-nginx"

images = `aws-vault exec administrator -- aws ecr-public describe-images --region us-east-1 --repository-name #{repository_name} --query 'imageDetails[*].imageDigest' --output json`
images = JSON.parse(images)
images.each_slice(100) do |batch|
  image_ids = batch.each_with_object([]) do |digest, result|
    result << {
      "imageDigest" => digest
    }
  end

  cli_json = {
    "registryId": "somleng",
    "repositoryName": repository_name,
    "imageIds": image_ids
  }.to_json

  p "executing: aws-vault exec administrator -- aws ecr-public batch-delete-image --region us-east-1 --cli-input-json '#{cli_json}'"
  `aws-vault exec administrator -- aws ecr-public batch-delete-image --region us-east-1 --cli-input-json '#{cli_json}'`
end
```

## PR

https://github.com/somleng/somleng/pull/1050

## Todo

* [x] Add ECR Lifecycle Policy
* [x] Tag github sha images with prefix to match against lifecycle policy
* [x] Make sure the lifecycle policy keeps the last x versions

**Comment by dwilkie** [comment]
Closed by #1050 and #1058
